### ISSUE TITLE
Kindly add Support for Typescript

### ISSUE THREAD

**Issue by mwangaben** [syropian/vue-input-autowidth#24]

**Comment by syropian** [comment]
Hi, could you expand a little on what type of TS support you’re looking for? I don’t personally use TypeScript with Vue very often, and since this component doesn’t really have much of a public API, I don’t really see the point? Do you just want typings first the config object or something?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by syropian** [comment]
Closed due to lack of author response.
